// import Image from "next/image";
// import Link from "next/link";
// import ProductCard from "./components/ProductCard";
// import { getServerSession } from "next-auth";
// import { authOptions } from "./api/auth/[...nextauth]/route";
// import Coffee from "../public/images/coffee.jpg";
// import type { Metadata } from 'next'

// export default async function Home() {
// //   return (
// //     <main className="relative h-screen">
// //       <Image
// //         src={"https://bit.ly/react-cover"}
// //         fill
// //         className="object-cover"
// //         sizes="(max-width: 480px) 100vw, (max-width: 768px) 50vw, 33vw"
// //         quality={75}
// //         priority
// //         alt="Coffee"
// //       />

// //     </main>
// //   );
// // }

// // export async function generateMetaData(): Promise<Metadata> {
// //   const product = await fetch('')

// //   return {
// //     title: `product.title`,
// //     description: '...'
// //   }
// // }

// // export const metadata: Metadata = {
// //   title: 'Create Next App',
// //   description: 'Generated by create next app',
// //   openGraph: {
// //     title: '......',
// //     description: '....'
// //   }
// // }

import Link from "next/link";
import ProductCard from "./components/ProductCard";
import { authOptions } from "./api/auth/authOptions";
import { getServerSession } from "next-auth";
import ShowButton from "./ShowButton";

export default async function Home() {
    const session = await getServerSession(authOptions)
  return (
    <main className="flex flex-col">
      <p>Hello World! {session && <span>{session.user!.name}</span>}</p>
      <Link href="/users">Users</Link>
      <ShowButton />
        {/* {isVisible && <HeavyComponent />} */}
        <ProductCard />
    </main>
  );
}
